import = [
    "~/.config/alacritty/themes/cobalt2.yaml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"

opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 19