#!/bin/bash
set -e

# hacky "fix"
mkdir  -p ~/.local/bin

DOTFILES="$(dirname "$(realpath "$0")")"
CONFIG="$DOTFILES/config"
UTILS="$DOTFILES/utils"
MAC_CONFIG="$DOTFILES/mac"

# STOW_FOLDERS="alacritty,bat,bin,git,nvim,p10k,skhd,tmux,yabai,zsh"
STOW_FOLDERS_FILE="$MAC_CONFIG/.macos_dotfiles"
BACKUP_FILES_FILE="$STOW_FOLDERS_FILE"
DOTFILE_HISTORY="$MAC_CONFIG/.history_macos"

export DOTFILES CONFIG UTILS STOW_FOLDERS_FILE BACKUP_FILES_FILE DOTFILES DOTFILE_HISTORY
$UTILS/backup
$UTILS/install