#!/bin/bash
set -e

PREV_STOW_FOLDERS=""
if [[ -f "$DOTFILE_HISTORY" ]]; then
    PREV_STOW_FOLDERS=$(cat "$DOTFILE_HISTORY")
fi

CURRENT_FOLDERS=$(cat "$STOW_FOLDERS_FILE")

pushd "$CONFIG" >/dev/null
# Unstow folders that are no longer in STOW_FOLDERS
for folder in $PREV_STOW_FOLDERS; do
    stow -D $folder
done

# Stow current folders
for folder in $CURRENT_FOLDERS; do
    echo "stow $folder"
    stow  --ignore=.DS_Store -t ~ $folder
done

# Update the dotfile history without duplicates
awk '{ print }' "$DOTFILE_HISTORY" "$STOW_FOLDERS_FILE" | sort -u > temp_file && mv temp_file "$DOTFILE_HISTORY"
popd >/dev/null